language: java

jobs:
  include:
    - stage: Docker
      if: branch = master
      script: ./gradlew dockerPush
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: Heroku
      if: branch = master

addons:
  sonarcloud:
    organization: $SONAR_USER
    token:
      secure: $SONAR_TOKEN



jdk:
  - openjdk11
