language: java

jobs:
  include:
    - stage: CodeQuality
      script: ./gradlew sonarqube
    - stage: Docker
      if: branch = master
      script: ./gradlew dockerPush
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: Heroku
      if: branch = master
      script: ./gradlew build deployHeroku

addons:
  sonarcloud:
    organization: $SONAR_USER
    token:
      secure: $SONAR_TOKEN
  deploy:
    provider: heroku
    api_key:
      secure: $HEROKU_API_KEY


jdk:
  - openjdk11